### ISSUE TITLE
Clarification on `Header::message_len`

### ISSUE THREAD

**Issue by flxo** [esrlabs/someip#10]
The fn [Header::message_len](https://github.com/esrlabs/someip/blob/0d45944fc03e16f84f5bfb60e0e1779912e6d17b/src/types.rs#L82-L85) return the `length` field + 8 which sound fishy. What should be the scope of this fn? Just the header len?

**Comment by kruss** [comment]
The header's 4 byte "length" field at offest 4 covers the number of bytes after until end of message (rest of the header + payload),- so "length field + 8" is correct to get the total length of the complete message.

Use-case is eg. parsing from data containing several messages, so rest of data can be processed until all data is consumed: 

```
        match Message::from_slice(input) {
            Ok(Message::Sd(header, payload)) => {
                let len = header.message_len();
                Ok((
                    &input[len..],
        ...
```

An alternative would also be: `Header::LENGTH + payload.len()`,- but here payload.len() would get calculated from its content.

**Comment by flxo** [comment]
Thanks for clarification! This is really confusing.
