### ISSUE TITLE
SD parsing errors

### ISSUE THREAD

**Issue by flxo** [esrlabs/someip#9]
When parsing SD messages a assumption is done: The reader will not produce more byte than needed to parse exactly one message: https://github.com/esrlabs/someip/blob/6a414b8396424f19f679174fae36963cb28ed52b/src/parser.rs#L128-L131

This piece of code hides IO errors and assumes that the reader ends after the message if there are no options.

**Comment by flxo** [comment]
Looks like the option field is not optional: https://github.com/esrlabs/someip/blob/6a414b8396424f19f679174fae36963cb28ed52b/src/serializer.rs#L107-L110 

-> if the `read_u32` returns a `Err` the fn should return that error instead of defaulting to `0`.

**Comment by kruss** [comment]
Agreed,- that should be changed to raise an error if the read fails.. same goes for the entries length:

```
        let entries_len: usize = match reader.read_u32::<BE>() {
            Ok(value) => value as usize,
            Err(_) => 0usize,
        };
```
